const Discord = require('discord.js')

exports.run = (client, message, args) => {
  if (message.channel.nsfw === true) {
  if ( message.react(':flag_tr:')) {
      var gif = [
      'http://porngif.top/gif/koureni/0001.gif',
      'http://porngif.top/gif/koureni/0002.gif',
      'http://porngif.top/gif/koureni/0003.gif',
      'http://porngif.top/gif/koureni/0004.gif',
      'http://porngif.top/gif/koureni/0005.gif',
      'http://porngif.top/gif/koureni/0006.gif',
      'http://porngif.top/gif/koureni/0007.gif',
      'http://porngif.top/gif/koureni/0008.gif',
      'http://porngif.top/gif/koureni/0009.gif',
      'http://porngif.top/gif/koureni/0010.gif',
      'http://porngif.top/gif/koureni/0011.gif',
      'http://porngif.top/gif/koureni/0012.gif',
      'http://porngif.top/gif/koureni/0013.gif',
      'http://porngif.top/gif/koureni/0014.gif',
      'http://porngif.top/gif/koureni/0015.gif',
      'http://porngif.top/gif/koureni/0016.gif',
      'http://porngif.top/gif/koureni/0017.gif',
      'http://porngif.top/gif/koureni/0018.gif',
      'http://porngif.top/gif/koureni/0019.gif',
      'http://porngif.top/gif/koureni/0020.gif',
      'http://porngif.top/gif/koureni/0021.gif',
      'http://porngif.top/gif/koureni/0022.gif',
      'http://porngif.top/gif/koureni/0023.gif',
      'http://porngif.top/gif/koureni/0024.gif',
      'http://porngif.top/gif/koureni/0025.gif',
      'http://porngif.top/gif/koureni/0026.gif',
      'http://porngif.top/gif/koureni/0027.gif',
      'http://porngif.top/gif/koureni/0028.gif',
      'http://porngif.top/gif/koureni/0029.gif',
      'http://porngif.top/gif/koureni/0030.gif',
      'http://porngif.top/gif/koureni/0031.gif',
      'http://porngif.top/gif/koureni/0032.gif',
      'http://porngif.top/gif/koureni/0033.gif',
      'http://porngif.top/gif/koureni/0034.gif',
      'http://porngif.top/gif/koureni/0035.gif',
      'http://porngif.top/gif/koureni/0036.gif',
      'http://porngif.top/gif/koureni/0037.gif',
      'http://porngif.top/gif/koureni/0038.gif',
      'http://porngif.top/gif/koureni/0039.gif',
      'http://porngif.top/gif/koureni/0040.gif',
      'http://porngif.top/gif/koureni/0041.gif',
      'http://porngif.top/gif/koureni/0042.gif',
      'http://porngif.top/gif/koureni/0043.gif',
      'http://porngif.top/gif/koureni/0044.gif',
      'http://porngif.top/gif/koureni/0043.gif',
      'http://porngif.top/gif/koureni/0044.gif',
      'http://porngif.top/gif/koureni/0045.gif',
      'http://porngif.top/gif/koureni/0046.gif',
      'http://porngif.top/gif/koureni/0047.gif',
      'http://porngif.top/gif/koureni/0048.gif',
      'http://porngif.top/gif/koureni/0049.gif',
      'http://porngif.top/gif/koureni/0050.gif',
      'http://porngif.top/gif/koureni/0051.gif',
      'http://porngif.top/gif/koureni/0052.gif',
      'http://porngif.top/gif/koureni/0053.gif',
      'http://porngif.top/gif/koureni/0054.gif',
      'http://porngif.top/gif/koureni/0055.gif',
      'http://porngif.top/gif/koureni/0056.gif',
      'http://porngif.top/gif/koureni/0057.gif',
      'http://porngif.top/gif/koureni/0058.gif',
      'http://porngif.top/gif/koureni/0059.gif',
      'http://porngif.top/gif/koureni/0060.gif',
      'http://porngif.top/gif/koureni/0061.gif',
      'http://porngif.top/gif/koureni/0062.gif',
      'http://porngif.top/gif/koureni/0063.gif',
      'http://porngif.top/gif/koureni/0064.gif',
      'http://porngif.top/gif/koureni/0065.gif',
      'http://porngif.top/gif/koureni/0066.gif',
      'http://porngif.top/gif/koureni/0067.gif',
      'http://porngif.top/gif/koureni/0068.gif',
      'http://porngif.top/gif/koureni/0069.gif',
      'http://porngif.top/gif/koureni/0070.gif',
      'http://porngif.top/gif/koureni/0071.gif',
      'http://porngif.top/gif/koureni/0072.gif',
      'http://porngif.top/gif/koureni/0073.gif',
      'http://porngif.top/gif/koureni/0074.gif',
      'http://porngif.top/gif/koureni/0075.gif',
      'http://porngif.top/gif/koureni/0076.gif',
      'http://porngif.top/gif/koureni/0077.gif',
      'http://porngif.top/gif/koureni/0078.gif',
      'http://porngif.top/gif/koureni/0079.gif',
      'http://porngif.top/gif/koureni/0080.gif',
      'http://porngif.top/gif/koureni/0081.gif',
      'http://porngif.top/gif/koureni/0082.gif',
      'http://porngif.top/gif/koureni/0083.gif',
      'http://porngif.top/gif/koureni/0084.gif',
      'http://porngif.top/gif/koureni/0085.gif',
      'http://porngif.top/gif/koureni/0086.gif',
      'http://porngif.top/gif/koureni/0087.gif',
      'http://porngif.top/gif/koureni/0088.gif',
      'http://porngif.top/gif/koureni/0089.gif',
      'http://porngif.top/gif/koureni/0090.gif',
      'http://porngif.top/gif/koureni/0091.gif',
      'http://porngif.top/gif/koureni/0092.gif',
      'http://porngif.top/gif/koureni/0093.gif',
      'http://porngif.top/gif/koureni/0094.gif',
      'http://porngif.top/gif/koureni/0095.gif',
      'http://porngif.top/gif/koureni/0096.gif',
      'http://porngif.top/gif/koureni/0097.gif',
      'http://porngif.top/gif/koureni/0098.gif',
      'http://porngif.top/gif/koureni/0099.gif',
      'http://porngif.top/gif/koureni/0100.gif',
      'http://porngif.top/gif/koureni/0101.gif',
      'http://porngif.top/gif/koureni/0102.gif',
      'http://porngif.top/gif/koureni/0103.gif',
      'http://porngif.top/gif/koureni/0104.gif',
      'http://porngif.top/gif/koureni/0105.gif',
      'http://porngif.top/gif/koureni/0106.gif',
      'http://porngif.top/gif/koureni/0107.gif',
      'http://porngif.top/gif/koureni/0108.gif',
      'http://porngif.top/gif/koureni/0109.gif',
      'http://porngif.top/gif/koureni/0110.gif',
      'http://porngif.top/gif/koureni/0111.gif',
      'http://porngif.top/gif/koureni/0112.gif',
      'http://porngif.top/gif/koureni/0113.gif',
      'http://porngif.top/gif/koureni/0114.gif',
      'http://porngif.top/gif/koureni/0115.gif',
      'http://porngif.top/gif/koureni/0116.gif',
      'http://porngif.top/gif/koureni/0117.gif',
      'http://porngif.top/gif/koureni/0118.gif',
      'http://porngif.top/gif/koureni/0119.gif',
      'http://porngif.top/gif/koureni/0120.gif',
      'http://porngif.top/gif/koureni/0121.gif',
      'http://porngif.top/gif/koureni/0122.gif',
      'http://porngif.top/gif/koureni/0123.gif',
      'http://porngif.top/gif/koureni/0124.gif',
      'http://porngif.top/gif/koureni/0125.gif',
      'http://porngif.top/gif/koureni/0126.gif',
      'http://porngif.top/gif/koureni/0127.gif',
      'http://porngif.top/gif/koureni/0128.gif',
      'http://porngif.top/gif/koureni/0129.gif',
      'http://porngif.top/gif/koureni/0130.gif',
      'http://porngif.top/gif/koureni/0131.gif',
      'http://porngif.top/gif/koureni/0132.gif',
      'http://porngif.top/gif/koureni/0133.gif',
      'http://porngif.top/gif/koureni/0134.gif',
      'http://porngif.top/gif/koureni/0135.gif',
      'http://porngif.top/gif/koureni/0136.gif',
      'http://porngif.top/gif/koureni/0137.gif',
      'http://porngif.top/gif/koureni/0138.gif',
      'http://porngif.top/gif/koureni/0139.gif',
      'http://porngif.top/gif/koureni/0140.gif',
      'http://porngif.top/gif/koureni/0141.gif',
      'http://porngif.top/gif/koureni/0142.gif',
      'http://porngif.top/gif/koureni/0143.gif'];

      var gifler = gif[Math.floor(Math.random() * gif.length)];
  }

    if (message.react(':flag_tr:')) {
    const op = new Discord.RichEmbed()
    .setDescription(`**Birileri Çavuşu Tokatlıyor**`)
    .setColor('RANDOM')
    .setImage(gifler)
    .setFooter(`${message.author.tag} | Free nudes thanks to Replica <3`)
    return message.channel.send(op)
    }
  } else {
       message.channel.send({embed: {
color: Math.floor(Math.random() * (0xFFFFFF + 1)),
description: ('Bu kanal NSFW(Not Safe For Work) kanalı değil. Daha fazla bilgi için **!nsfw-yardım** komutunu kullanabilirsiniz.')
}})
}
};


exports.conf = {
  enabled: true,
  guildOnly: false,
  aliases: [''],
  permLevel: 0
};

exports.help = {
  name: 'blowjob',
  description: 'Konusu blowjob olan random gifler gönderir.',
  usage: ''
};
