const Discord = require('discord.js')

exports.run = (client, message, args) => {
  if (message.channel.nsfw === true) {
  if ( message.react(':flag_tr:')) {
      var gif = [
      'https://wetgif.com/wp-content/uploads/gifs-cunnilingus-44.gif',
      'https://wetgif.com/wp-content/uploads/gentle-sex-58.gif',
      'https://wetgif.com/wp-content/uploads/porno-gif-funny-43.gif',
      'https://wetgif.com/wp-content/uploads/gentle-sex-33.gif',
      'https://wetgif.com/wp-content/uploads/anal-26.gif',
      'https://wetgif.com/wp-content/uploads/anal-72.gif',
      'https://wetgif.com/wp-content/uploads/doggie-style-74.gif',
      'https://wetgif.com/wp-content/uploads/doggie-style-17.gif',
      'https://wetgif.com/wp-content/uploads/doggie-style-42.gif',
      'https://wetgif.com/wp-content/uploads/doggie-style-22.gif',
      'https://wetgif.com/wp-content/uploads/doggie-style-20.gif',
      'https://wetgif.com/wp-content/uploads/porno-anime-11.gif',
      'https://wetgif.com/wp-content/uploads/porno-anime-13.gif',
      'https://wetgif.com/wp-content/uploads/porno-anime-10.gif',
      'https://wetgif.com/wp-content/uploads/porno-anime-22.gif',
      'https://wetgif.com/wp-content/uploads/gentle-sex-52.gif',
      'https://wetgif.com/wp-content/uploads/gentle-sex-29.gif',
      'https://wetgif.com/wp-content/uploads/beautiful-sex-85.gif',
      'https://wetgif.com/awp-content/uploads/beautiful-sex-92.gif',
      'https://wetgif.com/wp-content/uploads/beautiful-sex-91.gif',
      'https://wetgif.com/wp-content/uploads/porno-gif-69-63.gif',
      'http://porngif.it/gif/ze%20zadu/0715.gif',
      'http://porngif.it/gif/ze%20zadu/0244.gif',
      'http://porngif.it/gif/ze%20zadu/0798.gif',
      'http://porngif.it/gif/ze%20zadu/0133.gif',
      'http://porngif.it/gif/ze%20zadu/0820.gif',
      'http://porngif.it/gif/ze%20zadu/0641.gif',
      'http://porngif.it/gif/ze%20zadu/0790.gif',
      'http://porngif.it/gif/ze%20zadu/0541.gif',
      'http://porngif.it/gif/ze%20zadu/0580.gif',
      'http://porngif.top/gif/ze%20predu/0128.gif',
      'http://porngif.top/gif/koureni/0251.gif',
      'http://porngif.top/gif/koureni/0160.gif',
      'http://porngif.top/gif/prsa/0272.gif',
      'http://porngif.top/gif/na%20konicka/0404.gif',
      'http://porngif.top/gif/ze%20zadu/0782.gif',
      'http://porngif.top/gif/prsa/0191.gif',
      'http://porngif.top/gif/ze%20predu/0234.gif',
      'http://porngif.top/gif/na%20konicka/0503.gif',
      'http://porngif.top/gif/koureni/0354.gif',
      'http://porngif.top/gif/na%20konicka/0435.gif',
      'http://porngif.top/gif/koureni/0407.gif',
      'http://porngif.top/gif/koureni/0570.gif',
      'http://porngif.top/gif/koureni/0388.gif',
      'http://porngif.top/gif/ze%20predu/0486.gif',
      'http://porngif.top/gif/koureni/0388.gif',
      'http://porngif.top/gif/na%20konicka/0531.gif',
      'http://porngif.top/gif/koureni/0217.gif',
      'http://porngif.top/gif/ze%20predu/0446.gif',
      'http://porngif.top/gif/na%20konicka/0381.gif',
      'http://porngif.top/gif/prsa/0088.gif',
      'http://porngif.it/gif/ze%20zadu/0388.gif',
      'http://porngif.it/gif/ze%20zadu/0452.gif',
      'http://porngif.it/gif/ze%20zadu/0351.gif',
      'http://porngif.it/gif/ze%20zadu/0145.gif',
      'http://porngif.it/gif/ze%20zadu/0834.gif',
      'http://porngif.it/gif/ze%20zadu/0697.gif',
      'http://porngif.it/gif/ze%20zadu/0431.gif',
      'http://porngif.it/gif/ze%20zadu/0604.gif',
      'http://porngif.it/gif/ze%20zadu/0127.gif',
      'http://porngif.it/gif/ze%20zadu/0099.gif',
      'http://porngif.it/gif/ze%20zadu/0767.gif',
      'http://porngif.it/gif/ze%20zadu/0644.gif',
      'http://porngif.it/gif/ze%20zadu/0496.gif',
      'http://porngif.it/gif/ze%20zadu/0293.gif',
      'http://porngif.it/gif/ze%20zadu/0078.gif',
      'http://porngif.it/gif/ze%20zadu/0396.gif',
      'http://porngif.it/gif/ze%20zadu/0737.gif',
      'http://porngif.it/gif/ze%20zadu/0297.gif',
      'http://porngif.it/gif/ze%20zadu/0605.gif',
      'http://porngif.it/gif/ze%20zadu/0252.gif',
      'http://porngif.it/gif/ze%20zadu/0291.gif',
      'http://porngif.it/gif/ze%20zadu/0389.gif',
      'http://porngif.it/gif/ze%20zadu/0664.gif',
      'https://wetgif.com/wp-content/uploads/porno-gif-chulki-23.gif',
      'https://wetgif.com/wp-content/uploads/porno-gif-chulki-27.gif',
      'https://wetgif.com/wp-content/uploads/porno-gif-chulki-1.gif',
      'https://wetgif.com/wp-content/uploads/porno-gif-chulki-42.gif',
      'https://wetgif.com/wp-content/uploads/porno-gif-chulki-2.gif',
      'https://wetgif.com/wp-content/uploads/porno-gif-chulki-5.gif',
      'https://wetgif.com/wp-content/uploads/porno-gif-chulki-6.gif',
      'http://porngif.top/gif/zadky/0148.gif',
      'https://images-ext-1.discordapp.net/external/JrQ__Z9jDZBVtWYGGZ-6zGGAWR6RZ58qQqdDBpS2C3A/https/cdn.boob.bot/boobs/80008D12.gif',
      'https://images-ext-1.discordapp.net/external/CHA6IkSEOpIsPOs6pIGcZ1BpIPtrDy4PyMJDlAjEZNs/https/cdn.boob.bot/boobs/8000BF53.gif',
      'https://images-ext-1.discordapp.net/external/DENYpJrpTsopApznt_KmyK5REwOaHNeXaMbSY4lLhhM/https/cdn.boob.bot/Gifs/19B1.gif',
      'https://images-ext-2.discordapp.net/external/8yYMyCkKsDDgvM9f3FRpVQU4L4UQGRzRauy_cnMHHjI/https/cdn.boob.bot/Gifs/17E2.gif',
      'https://images-ext-1.discordapp.net/external/ODACY5-ktE-jD3_uek6tZ1Wd0tjUzz-BdBpDcOYLc1s/https/cdn.boob.bot/boobs/80006652.gif',
      'https://cdn.boob.bot/boobs/80006CFB.gif',
      'https://cdn.boob.bot/boobs/8000743F.gif',
      'https://images-ext-2.discordapp.net/external/7fY7O46-AYAEtjsYZu4vKd3XYjcPe2oRDncNCV5qBnk/https/cdn.boob.bot/boobs/80010F3F.gif',
      'https://images-ext-1.discordapp.net/external/ZvXt3mwpR3ckeUe6MhhgEiDLeJxgiae9S61rW8bLVpc/https/cdn.boob.bot/boobs/800140E5.gif',
      'https://cdn.boob.bot/boobs/80010F3F.gif',
      'https://images-ext-1.discordapp.net/external/VWBpZDczi7Gg7W7kyslGf2IJpUoYFrDMBTuWkqAKSUM/https/cdn.boob.bot/boobs/8000E87F.gif',
      'https://images-ext-1.discordapp.net/external/xwKFVWyqzdE8IsdsDBEyvGvm2AvrqCaZZxSUSWLAeOQ/https/cdn.boob.bot/boobs/8000118E.gif',
      'https://images-ext-2.discordapp.net/external/XSE-8ldi2SwEF8z6L9682K3kTJNcZgW8hQ3oZ3LTQYM/https/cdn.boob.bot/boobs/80002F39.gif',
      'https://images-ext-1.discordapp.net/external/ZmvQlK0_dg5IY1TpInq3lcX8Yw9y1ThXjmYyRqozyFE/https/cdn.boob.bot/boobs/80003F92.gif',
      'https://images-ext-1.discordapp.net/external/jVWFHxzrtvFw21dtv-yxD2OLnOJ7MeMY7yI2ZcjewDQ/https/cdn.boob.bot/boobs/800174F7.gif',
      'http://porngif.it/gif/ze%20zadu/0739.gif',
      'http://porngif.it/gif/ze%20zadu/0720.gif',
      'http://porngif.it/gif/ze%20zadu/0815.gif',
      //100
      'http://porngif.it/gif/ze%20zadu/0685.gif',
      'http://porngif.it/gif/ze%20zadu/0104.gif',
      'http://porngif.it/gif/ze%20zadu/0079.gif',
      'http://porngif.it/gif/ze%20zadu/0169.gif',
      'http://porngif.it/gif/ze%20zadu/0079.gif',
      'http://porngif.it/gif/ze%20zadu/0626.gif',
      'http://porngif.it/gif/ze%20zadu/0738.gif',
      'http://porngif.it/gif/ze%20zadu/0233.gif',
      'http://porngif.it/gif/ze%20zadu/0768.gif',
      'http://porngif.it/gif/ze%20zadu/0115.gif',
      'http://porngif.it/gif/ze%20zadu/0525.gif',
      'http://porngif.it/gif/ze%20zadu/0323.gif',
      'http://porngif.it/gif/ze%20zadu/0804.gif',
      'http://porngif.it/gif/ze%20zadu/0153.gif',
      'http://porngif.it/gif/ze%20zadu/0443.gif',
      'http://porngif.it/gif/ze%20zadu/0830.gif',
      'http://porngif.it/gif/ze%20zadu/0156.gif',
      'http://porngif.it/gif/ze%20zadu/0231.gif',
      'http://porngif.it/gif/ze%20zadu/0725.gif',
      'http://porngif.it/gif/ze%20zadu/0355.gif',
      'http://porngif.it/gif/ze%20zadu/0514.gif',
      'http://porngif.it/gif/ze%20zadu/0338.gif',
      'http://porngif.it/gif/ze%20zadu/0609.gif',
      'http://porngif.it/gif/ze%20zadu/0347.gif',
      'http://porngif.it/gif/ze%20zadu/0244.gif',
      'http://porngif.it/gif/ze%20zadu/0649.gif',
      'http://porngif.it/gif/ze%20zadu/0658.gif',
      'http://porngif.it/gif/ze%20zadu/0042.gif',
      'http://porngif.it/gif/ze%20zadu/0592.gif',
      'http://porngif.it/gif/ze%20zadu/0452.gif',
      'http://porngif.it/gif/ze%20zadu/0427.gif',
      'http://porngif.it/gif/ze%20zadu/0054.gif',
      'http://porngif.it/gif/ze%20zadu/0696.gif',
      'http://porngif.it/gif/ze%20zadu/0385.gif',
      'http://porngif.it/gif/ze%20zadu/0024.gif',
      'http://porngif.it/gif/ze%20zadu/0617.gif',
      'http://porngif.it/gif/ze%20zadu/0681.gif',
      'http://porngif.it/gif/ze%20zadu/0382.gif',
      'http://porngif.it/gif/ze%20zadu/0561.gif',
      'http://porngif.it/gif/ze%20zadu/0408.gif',
      'http://porngif.it/gif/ze%20zadu/0257.gif',
      'http://porngif.it/gif/ze%20zadu/0628.gif',
      'http://porngif.it/gif/ze%20zadu/0351.gif',
      'http://porngif.it/gif/ze%20zadu/0669.gif',
      'http://porngif.it/gif/ze%20zadu/0005.gif',
      'http://porngif.it/gif/ze%20zadu/0223.gif',
      'http://porngif.it/gif/ze%20zadu/0526.gif',
      'http://porngif.it/gif/ze%20zadu/0516.gif',
      'http://porngif.it/gif/ze%20zadu/0675.gif',
      'http://porngif.it/gif/ze%20zadu/0574.gif',
      'http://porngif.it/gif/ze%20zadu/0331.gif',
      'http://porngif.it/gif/ze%20zadu/0299.gif',
      'http://porngif.it/gif/ze%20zadu/0456.gif',
      'http://porngif.it/gif/ze%20zadu/0060.gif',
      'http://porngif.it/gif/ze%20zadu/0477.gif',
      'http://porngif.it/gif/ze%20zadu/0178.gif',
      'http://porngif.it/gif/ze%20zadu/0636.gif',
      'http://porngif.it/gif/ze%20zadu/0049.gif',
      'http://porngif.it/gif/ze%20zadu/0105.gif',
      'http://porngif.it/gif/ze%20zadu/0776.gif',
      'http://porngif.it/gif/ze%20zadu/0386.gif',
      'http://porngif.it/gif/ze%20zadu/0766.gif',
      'http://porngif.it/gif/ze%20zadu/0312.gif',
      'http://porngif.it/gif/ze%20zadu/0354.gif',
      'http://porngif.it/gif/ze%20zadu/0340.gif',
      'http://porngif.it/gif/ze%20zadu/0743.gif',
      'http://porngif.it/gif/ze%20zadu/0111.gif',
      'http://porngif.it/gif/ze%20zadu/0692.gif',
      'http://porngif.it/gif/ze%20zadu/0349.gif',
      'http://porngif.it/gif/ze%20zadu/0684.gif',
      'http://porngif.it/gif/ze%20zadu/0253.gif',
      'http://porngif.it/gif/ze%20zadu/0336.gif',
      'http://porngif.it/gif/ze%20zadu/0356.gif',
      'http://porngif.it/gif/ze%20zadu/0512.gif',
      'http://porngif.it/gif/ze%20zadu/0710.gif',
      'http://porngif.it/gif/ze%20zadu/0344.gif',
      'http://porngif.it/gif/ze%20zadu/0419.gif',
      'http://porngif.it/gif/ze%20zadu/0255.gif',
      'http://porngif.it/gif/ze%20zadu/0184.gif',
      'http://porngif.it/gif/ze%20zadu/0836.gif',
      'http://porngif.it/gif/ze%20zadu/0240.gif',
      'http://porngif.it/gif/ze%20zadu/0267.gif',
      'http://porngif.it/gif/ze%20zadu/0465.gif',
      'http://porngif.it/gif/ze%20zadu/0767.gif',
      'http://porngif.it/gif/ze%20zadu/0070.gif',
      'http://porngif.it/gif/ze%20zadu/0086.gif',
      'http://porngif.it/gif/ze%20zadu/0767.gif',
      'http://porngif.it/gif/ze%20zadu/0051.gif',
      'http://porngif.it/gif/ze%20zadu/0145.gif',
      'http://porngif.it/gif/ze%20zadu/0350.gif',
      'http://porngif.it/gif/ze%20zadu/0375.gif',
      'http://porngif.it/gif/ze%20zadu/0216.gif',
      'http://porngif.it/gif/ze%20zadu/0521.gif',
      'http://porngif.it/gif/ze%20zadu/0678.gif',
      'http://porngif.it/gif/ze%20zadu/0077.gif',
      //200
      'http://porngif.it/gif/ze%20zadu/0214.gif',
      'http://porngif.it/gif/ze%20zadu/0261.gif',
      'http://porngif.it/gif/ze%20zadu/0387.gif',
      'http://porngif.it/gif/ze%20zadu/0037.gif',
      'http://porngif.it/gif/ze%20zadu/0074.gif',
      'http://porngif.it/gif/ze%20zadu/0447.gif',
      'http://porngif.it/gif/ze%20zadu/0584.gif',
      'http://porngif.it/gif/ze%20zadu/0206.gif',
      'http://porngif.it/gif/ze%20zadu/0372.gif',
      'http://porngif.it/gif/ze%20zadu/0020.gif',
      'http://porngif.it/gif/ze%20zadu/0069.gif',
      'http://porngif.it/gif/ze%20zadu/0247.gif',
      'http://porngif.it/gif/ze%20zadu/0434.gif',
      'http://porngif.it/gif/ze%20zadu/0378.gif',
      'http://porngif.it/gif/ze%20zadu/0474.gif',
      'http://porngif.it/gif/ze%20zadu/0797.gif',
      'http://porngif.it/gif/ze%20zadu/0802.gif',
      'http://porngif.it/gif/ze%20zadu/0702.gif',
      'http://porngif.it/gif/ze%20zadu/0635.gif',
      'http://porngif.it/gif/ze%20zadu/0733.gif',
      'http://porngif.it/gif/ze%20zadu/0117.gif',
      'http://porngif.it/gif/ze%20zadu/0641.gif',
      'http://porngif.it/gif/ze%20zadu/0360.gif',
      'http://porngif.it/gif/ze%20zadu/0315.gif',
      'http://porngif.it/gif/ze%20zadu/0706.gif',
      'http://porngif.it/gif/ze%20zadu/0033.gif',
      'http://porngif.it/gif/ze%20zadu/0515.gif',
      'http://porngif.it/gif/ze%20zadu/0140.gif',
      'http://porngif.it/gif/ze%20zadu/0622.gif',
      'http://porngif.it/gif/ze%20zadu/0515.gif',
      'http://porngif.it/gif/ze%20zadu/0737.gif',
      'http://porngif.it/gif/ze%20zadu/0693.gif',
      'http://porngif.it/gif/ze%20zadu/0034.gif',
      'http://porngif.it/gif/ze%20zadu/0654.gif',
      'http://porngif.it/gif/ze%20zadu/0691.gif',
      'http://porngif.it/gif/ze%20zadu/0165.gif',
      'http://porngif.it/gif/ze%20zadu/0467.gif',
      'http://porngif.it/gif/ze%20zadu/0268.gif',
      'http://porngif.it/gif/ze%20zadu/0318.gif',
      'http://porngif.it/gif/ze%20zadu/0606.gif',
      'http://porngif.it/gif/ze%20zadu/0715.gif',
      'http://porngif.it/gif/ze%20zadu/0823.gif',
      'http://porngif.it/gif/ze%20zadu/0437.gif',
      'http://porngif.it/gif/ze%20zadu/0150.gif',
      'http://porngif.it/gif/ze%20zadu/0303.gif',
      'http://porngif.it/gif/ze%20zadu/0437.gif',
      'http://porngif.it/gif/ze%20zadu/0421.gif',
      'http://porngif.it/gif/ze%20zadu/0809.gif',
      'http://porngif.it/gif/ze%20zadu/0734.gif',
      'http://porngif.it/gif/ze%20zadu/0066.gif',
      'http://porngif.it/gif/ze%20zadu/0530.gif',
      'http://porngif.it/gif/ze%20zadu/0582.gif',
      'http://porngif.it/gif/ze%20zadu/0441.gif',
      'http://porngif.it/gif/ze%20zadu/0090.gif',
      'http://porngif.it/gif/ze%20zadu/0834.gif',
      'http://porngif.it/gif/ze%20zadu/0807.gif',
      'http://porngif.it/gif/ze%20zadu/0044.gif',
      'http://porngif.it/gif/ze%20zadu/0542.gif',
      'http://porngif.it/gif/ze%20zadu/0043.gif',
      'http://porngif.it/gif/ze%20zadu/0522.gif',
      'http://porngif.it/gif/ze%20zadu/0254.gif',
      'http://porngif.it/gif/ze%20zadu/0064.gif',
      'http://porngif.it/gif/ze%20zadu/0838.gif',
      'http://porngif.it/gif/ze%20zadu/0811.gif',
      'http://porngif.it/gif/ze%20zadu/0777.gif',
      'http://porngif.it/gif/ze%20zadu/0485.gif',
      //359
      'https://wetgif.com/wp-content/uploads/porno-gif-funny-43.gif'];

      var gifler = gif[Math.floor(Math.random() * gif.length)];
  }

    if (message.react(':flag_tr:')) {
    const op = new Discord.RichEmbed()
    .setDescription(`**Birileri Çavuşu Tokatlıyor**`)
    .setColor('RANDOM')
    .setImage(gifler)
    .setFooter(`${message.author.tag} | Free nudes thanks to Replica <3`)
    return message.channel.send(op)
  }
} else {
  message.channel.send({embed: {
color: Math.floor(Math.random() * (0xFFFFFF + 1)),
description: ('Bu kanal NSFW(Not Safe For Work) kanalı değil. Daha fazla bilgi için **!nsfw-yardım** komutunu kullanabilirsiniz.')
}})
}
};


exports.conf = {
  enabled: true,
  guildOnly: false,
  aliases: [''],
  permLevel: 0
};

exports.help = {
  name: 'nsfw',
  description: 'Random gifler gönderir.',
  usage: ''
};
