const Discord = require('discord.js')

exports.run = (client, message, args) => {
  if (message.channel.nsfw === true) {
  if ( message.react(':flag_tr:')) {
      var gif = [
      'http://porngif.top/gif/kundicky/0001.gif',
      'http://porngif.top/gif/kundicky/0002.gif',
      'http://porngif.top/gif/kundicky/0003.gif',
      'http://porngif.top/gif/kundicky/0004.gif',
      'http://porngif.top/gif/kundicky/0005.gif',
      'http://porngif.top/gif/kundicky/0006.gif',
      'http://porngif.top/gif/kundicky/0007.gif',
      'http://porngif.top/gif/kundicky/0008.gif',
      'http://porngif.top/gif/kundicky/0009.gif',
      'http://porngif.top/gif/kundicky/0010.gif',
      'http://porngif.top/gif/kundicky/0011.gif',
      'http://porngif.top/gif/kundicky/0012.gif',
      'http://porngif.top/gif/kundicky/0013.gif',
      'http://porngif.top/gif/kundicky/0014.gif',
      'http://porngif.top/gif/kundicky/0015.gif',
      'http://porngif.top/gif/kundicky/0016.gif',
      'http://porngif.top/gif/kundicky/0017.gif',
      'http://porngif.top/gif/kundicky/0018.gif',
      'http://porngif.top/gif/kundicky/0019.gif',
      'http://porngif.top/gif/kundicky/0020.gif',
      'http://porngif.top/gif/kundicky/0021.gif',
      'http://porngif.top/gif/kundicky/0022.gif',
      'http://porngif.top/gif/kundicky/0023.gif',
      'http://porngif.top/gif/kundicky/0024.gif',
      'http://porngif.top/gif/kundicky/0025.gif',
      'http://porngif.top/gif/kundicky/0026.gif',
      'http://porngif.top/gif/kundicky/0027.gif',
      'http://porngif.top/gif/kundicky/0028.gif',
      'http://porngif.top/gif/kundicky/0029.gif',
      'http://porngif.top/gif/kundicky/0030.gif',
      'http://porngif.top/gif/kundicky/0031.gif',
      'http://porngif.top/gif/kundicky/0032.gif',
      'http://porngif.top/gif/kundicky/0033.gif',
      'http://porngif.top/gif/kundicky/0034.gif',
      'http://porngif.top/gif/kundicky/0035.gif',
      'http://porngif.top/gif/kundicky/0036.gif',
      'http://porngif.top/gif/kundicky/0037.gif',
      'http://porngif.top/gif/kundicky/0038.gif',
      'http://porngif.top/gif/kundicky/0039.gif',
      'http://porngif.top/gif/kundicky/0040.gif',
      'http://porngif.top/gif/kundicky/0041.gif',
      'http://porngif.top/gif/kundicky/0042.gif',
      'http://porngif.top/gif/kundicky/0043.gif',
      'http://porngif.top/gif/kundicky/0044.gif',
      'http://porngif.top/gif/kundicky/0045.gif',
      'http://porngif.top/gif/kundicky/0046.gif',
      'http://porngif.top/gif/kundicky/0047.gif',
      'http://porngif.top/gif/kundicky/0048.gif',
      'http://porngif.top/gif/kundicky/0049.gif',
      'http://porngif.top/gif/kundicky/0050.gif',
      'http://porngif.top/gif/kundicky/0051.gif',
      'http://porngif.top/gif/kundicky/0052.gif',
      'http://porngif.top/gif/kundicky/0053.gif',
      'http://porngif.top/gif/kundicky/0054.gif',
      'http://porngif.top/gif/kundicky/0055.gif',
      'http://porngif.top/gif/kundicky/0056.gif',
      'http://porngif.top/gif/kundicky/0057.gif',
      'http://porngif.top/gif/kundicky/0058.gif',
      'http://porngif.top/gif/kundicky/0059.gif',
      'http://porngif.top/gif/kundicky/0060.gif',
      'http://porngif.top/gif/kundicky/0061.gif',
      'http://porngif.top/gif/kundicky/0062.gif',
      'http://porngif.top/gif/kundicky/0063.gif',
      'http://porngif.top/gif/kundicky/0064.gif',
      'http://porngif.top/gif/kundicky/0065.gif',
      'http://porngif.top/gif/kundicky/0066.gif',
      'http://porngif.top/gif/kundicky/0067.gif',
      'http://porngif.top/gif/kundicky/0068.gif',
      'http://porngif.top/gif/kundicky/0069.gif',
      'http://porngif.top/gif/kundicky/0070.gif',
      'http://porngif.top/gif/kundicky/0071.gif',
      'http://porngif.top/gif/kundicky/0072.gif',
      'http://porngif.top/gif/kundicky/0073.gif',
      'http://porngif.top/gif/kundicky/0074.gif',
      'http://porngif.top/gif/kundicky/0075.gif',
      'http://porngif.top/gif/kundicky/0076.gif',
      'http://porngif.top/gif/kundicky/0077.gif',
      'http://porngif.top/gif/kundicky/0078.gif',
      'http://porngif.top/gif/kundicky/0079.gif',
      'http://porngif.top/gif/kundicky/0080.gif',
      'http://porngif.top/gif/kundicky/0081.gif',
      'http://porngif.top/gif/kundicky/0082.gif',
      'http://porngif.top/gif/kundicky/0083.gif',
      'http://porngif.top/gif/kundicky/0084.gif',
      'http://porngif.top/gif/kundicky/0085.gif',
      'http://porngif.top/gif/kundicky/0086.gif',
      'http://porngif.top/gif/kundicky/0087.gif',
      'http://porngif.top/gif/kundicky/0088.gif',
      'http://porngif.top/gif/kundicky/0089.gif',
      'http://porngif.top/gif/kundicky/0090.gif',
      'http://porngif.top/gif/kundicky/0091.gif',
      'http://porngif.top/gif/kundicky/0092.gif',
      'http://porngif.top/gif/kundicky/0093.gif',
      'http://porngif.top/gif/kundicky/0094.gif',
      'http://porngif.top/gif/kundicky/0095.gif',
      'http://porngif.top/gif/kundicky/0096.gif',
      'http://porngif.top/gif/kundicky/0097.gif',
      'http://porngif.top/gif/kundicky/0098.gif',
      'http://porngif.top/gif/kundicky/0099.gif',
      'http://porngif.top/gif/kundicky/0100.gif',
      'http://porngif.top/gif/kundicky/0101.gif',
      'http://porngif.top/gif/kundicky/0102.gif',
      'http://porngif.top/gif/kundicky/0103.gif',
      'http://porngif.top/gif/kundicky/0104.gif',
      'http://porngif.top/gif/kundicky/0105.gif',
      'http://porngif.top/gif/kundicky/0106.gif',
      'http://porngif.top/gif/kundicky/0107.gif',
      'http://porngif.top/gif/kundicky/0108.gif',
      'http://porngif.top/gif/kundicky/0109.gif',
      'http://porngif.top/gif/kundicky/0110.gif',
      'http://porngif.top/gif/kundicky/0111.gif',
      'http://porngif.top/gif/kundicky/0112.gif',
      'http://porngif.top/gif/kundicky/0113.gif',
      'http://porngif.top/gif/kundicky/0114.gif',
      'http://porngif.top/gif/kundicky/0115.gif',
      'http://porngif.top/gif/kundicky/0116.gif',
      'http://porngif.top/gif/kundicky/0117.gif',
      'http://porngif.top/gif/kundicky/0118.gif',
      'http://porngif.top/gif/kundicky/0119.gif',
      'http://porngif.top/gif/kundicky/0120.gif',
      'http://porngif.top/gif/kundicky/0121.gif',
      'http://porngif.top/gif/kundicky/0122.gif',
      'http://porngif.top/gif/kundicky/0123.gif',
      'http://porngif.top/gif/kundicky/0124.gif',
      'http://porngif.top/gif/kundicky/0125.gif',
      'http://porngif.top/gif/kundicky/0126.gif',
      'http://porngif.top/gif/kundicky/0127.gif',
      'http://porngif.top/gif/kundicky/0128.gif',
      'http://porngif.top/gif/kundicky/0129.gif',
      'http://porngif.top/gif/kundicky/0130.gif',
      'http://porngif.top/gif/kundicky/0131.gif',
      'http://porngif.top/gif/kundicky/0132.gif',
      'http://porngif.top/gif/kundicky/0133.gif',
      'http://porngif.top/gif/kundicky/0134.gif',
      'http://porngif.top/gif/kundicky/0135.gif',
      'http://porngif.top/gif/kundicky/0136.gif',
      'http://porngif.top/gif/kundicky/0137.gif',
      'http://porngif.top/gif/kundicky/0138.gif',
      'http://porngif.top/gif/kundicky/0139.gif',
      'http://porngif.top/gif/kundicky/0140.gif',
      'http://porngif.top/gif/kundicky/0141.gif',
      'http://porngif.top/gif/kundicky/0142.gif',
      'http://porngif.top/gif/kundicky/0143.gif',
      'http://porngif.top/gif/kundicky/0144.gif',
      'http://porngif.top/gif/kundicky/0145.gif',
      'http://porngif.top/gif/kundicky/0146.gif',
      'http://porngif.top/gif/kundicky/0147.gif',
      'http://porngif.top/gif/kundicky/0148.gif',
      'http://porngif.top/gif/kundicky/0149.gif',
      'http://porngif.top/gif/kundicky/0150.gif',
      'http://porngif.top/gif/kundicky/0151.gif',
      'http://porngif.top/gif/kundicky/0152.gif',
      'http://porngif.top/gif/kundicky/0153.gif',
      'http://porngif.top/gif/kundicky/0154.gif',
      'http://porngif.top/gif/kundicky/0155.gif',
      'http://porngif.top/gif/kundicky/0156.gif',
      'http://porngif.top/gif/kundicky/0157.gif',
      'http://porngif.top/gif/kundicky/0158.gif',
      'http://porngif.top/gif/kundicky/0159.gif',
      'http://porngif.top/gif/kundicky/0160.gif',
      'http://porngif.top/gif/kundicky/0161.gif',
      'http://porngif.top/gif/kundicky/0162.gif',
      'http://porngif.top/gif/kundicky/0163.gif',
      'http://porngif.top/gif/kundicky/0164.gif',
      'http://porngif.top/gif/kundicky/0165.gif',
      'http://porngif.top/gif/kundicky/0166.gif',
      'http://porngif.top/gif/kundicky/0167.gif',
      'http://porngif.top/gif/kundicky/0168.gif',
      'http://porngif.top/gif/kundicky/0169.gif',
      'http://porngif.top/gif/kundicky/0170.gif',
      'http://porngif.top/gif/kundicky/0171.gif',
      'http://porngif.top/gif/kundicky/0172.gif',
      'http://porngif.top/gif/kundicky/0173.gif',
      'http://porngif.top/gif/kundicky/0174.gif',
      'http://porngif.top/gif/kundicky/0175.gif',
      'http://porngif.top/gif/kundicky/0176.gif',
      'http://porngif.top/gif/kundicky/0177.gif',
      'http://porngif.top/gif/kundicky/0178.gif',
      'http://porngif.top/gif/kundicky/0136.gif'];

      var gifler = gif[Math.floor(Math.random() * gif.length)];
  }

    if (message.react(':flag_tr:')) {
    const op = new Discord.RichEmbed()
    .setDescription(`**Birileri Çavuşu Tokatlıyor**`)
    .setColor('RANDOM')
    .setImage(gifler)
    .setFooter(`${message.author.tag} | Free nudes thanks to Replica <3`)
    return message.channel.send(op)
    }
  } else {
       message.channel.send({embed: {
color: Math.floor(Math.random() * (0xFFFFFF + 1)),
description: ('Bu kanal NSFW(Not Safe For Work) kanalı değil. Daha fazla bilgi için **!nsfw-yardım** komutunu kullanabilirsiniz.')
}})
}
};


exports.conf = {
  enabled: true,
  guildOnly: false,
  aliases: [''],
  permLevel: 0
};

exports.help = {
  name: 'pussy',
  description: 'Konusu pussy olan random gifler gönderir.',
  usage: ''
};
